<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Admin\StationMasterRequestController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\StationMasterController;
use App\Http\Controllers\ProfileController;

/*
|--------------------------------------------------------------------------
| PUBLIC ROUTES (Always Accessible)
|--------------------------------------------------------------------------
*/

// Homepage — THIS MUST EXIST
Route::get('/', function () {
    return view('welcome');
})->name('home');

// Station Master Pending Page (after registration submission)
Route::get('/station-master/pending', function () {
    return view('auth.station-master-pending');
})->name('station-master.pending');

/*
|--------------------------------------------------------------------------
| BREEZE AUTH ROUTES (Keep these — they handle login/register/logout)
|--------------------------------------------------------------------------
*/

// Breeze default auth routes (login, register, forgot password, etc.)
// This file is generated by Breeze — DO NOT DELETE IT
require __DIR__.'/auth.php';

/*
|--------------------------------------------------------------------------
| CUSTOM ROLE LOGIN PAGES (Guest Only)
|--------------------------------------------------------------------------
*/

// Station Master dedicated login page
Route::get('/station-master/login', [AuthenticatedSessionController::class, 'create'])
    ->middleware('guest')
    ->name('station-master.login');

// Admin dedicated login page (privileged entry point)
Route::get('/admin/login', [AuthenticatedSessionController::class, 'create'])
    ->middleware('guest')
    ->name('admin.login');

/*
|--------------------------------------------------------------------------
| PASSENGER ROUTES (Auth + Verified)
|--------------------------------------------------------------------------
*/
Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

/*
|--------------------------------------------------------------------------
| STATION MASTER ROUTES (404 for non-station-masters)
|--------------------------------------------------------------------------
*/
Route::middleware(['auth', 'station_master'])->prefix('station-master')->group(function () {
    Route::get('/', [StationMasterController::class, 'dashboard'])->name('station-master.dashboard');
});

/*
|--------------------------------------------------------------------------
| ADMIN ROUTES (Privileged)
| Guest → redirect to /admin/login
| Logged-in non-admin → 404 (hide existence)
| Admin → full access
|--------------------------------------------------------------------------
*/
Route::middleware(['admin'])->prefix('admin')->group(function () {
    
    // Admin Dashboard
    Route::get('/', [AdminController::class, 'dashboard'])->name('admin.dashboard');

    // Station Master Request Management
    Route::get('/station-master-requests', [StationMasterRequestController::class, 'index'])
        ->name('admin.station-master-requests.index');
    
    Route::patch('/station-master-requests/{stationMasterRequest}/approve', [StationMasterRequestController::class, 'approve'])
        ->name('admin.station-master-requests.approve');
    
    Route::patch('/station-master-requests/{stationMasterRequest}/reject', [StationMasterRequestController::class, 'reject'])
        ->name('admin.station-master-requests.reject');
});

/*
|--------------------------------------------------------------------------
| PROFILE ROUTES (Breeze Default)
|--------------------------------------------------------------------------
*/
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});